comment:
  layout: "condensed_header, diff, flags, condensed_files"
  behavior: default
  require_changes: false

coverage:
  status:
    project:
      default:
        target: 80%
    patch:
      default:
        target: 80%

flags:
  common:
    paths:
      - common/src/main/
  identity-service:
    paths:
      - identity-service/src/main/
  authz-service:
    paths:
      - authz-service/src/main/
  audit-service:
    paths:
      - audit-service/src/main/
